### PR TITLE
fixing css issues

### PR DESCRIPTION
**Pull request by pqv199x**
image
image
image
Candidate transactions:
image
Voter transactions:
image

### CODE REVIEW

**Comment by pqv199x** [comment]
Yeah, np, can you check it for me
image

**Comment by etienne-napoleone** [comment]
Not sure, I think the ID collumn is useless here because it doesn't represent anything (click on page 2, it will still be ID 1 to 10). But we can keep it I guess.

But I see you made the opposite of what I thought, you made the spacing between row the same as the spacing between "masternode" and "vote" instead of the opposite, can you change that? I think it takes too much space.

**Comment by thanhson1085** [comment]
Yep, vote for removing id column

**Comment by etienne-napoleone** [comment]
@pqv199x did you fixed the spacing on the status and vote button?

**Comment by khaihkd** [comment]
I think we remove `ID` column in homepage, candidate detail, and replace with`Number` column, `Number` will grow up from `1` to `n`. It is just for count

**Comment by etienne-napoleone** [comment]
@khaihkd I agree, the ID collumn is actually always useless and give no usefull informations. I think it could be good to remove it everywhere.
I don't think a `Number` column would be usefull tho. it will just 1-10 all the time :/

**Comment by etienne-napoleone** [comment]
Also the ID on the Candidate list could be named "Rank" instead and be tied to their rank

**Comment by thanhson1085** [comment]
merged it, for fixing the space, do in another PR

**Pull request merged**
