### PR TITLE
Tomomaster: Ledger support

### PR DESCRIPTION
**Pull request by thanhnguyennguyen**
Hi a @thanhson1085 , @pqv199x ,
Could you please arrange your time help me review this pull request ?
Changes in this PR:
- Enable https
- Login, get account, balance using Ledger
- Vote, unvote using Ledger
- Apply, resign masternode candidate using Ledger
- Withdraw using Ledger

Thanks,
Nguyen Nguyen

### CODE REVIEW

**Comment by thanhnguyennguyen** [comment]
Ok. I will drop that commit out of this pull request 
after that I will push the commit to a new branch so that people can cherry-pick and enable https on their local environment

**Comment by thanhnguyennguyen** [comment]
Now we can cherry-pick this commit
692b9c5a9fa06a9eeabcf16913640847ab9725ce
to enable https on local environment

**Comment by thanhson1085** [comment]
I think that we should provide a option, so we can run https in local if needed
e.g: `npm run dev-https`

**Comment by thanhson1085** [comment]
Use webpack to enable https for dev enviroment: https://webpack.js.org/configuration/dev-server/#devserver-https

**Comment by thanhnguyennguyen** [comment]
Hi a @thanhson1085 ,
Please help me review again
Changes in this update:
- Allow users select addresses from their Ledger
in default: display first 10 addresses. Users can load more addresses

**Pull request merged**
